# Site settings
title: ARAF RAHMAN 
header-img: img/home-bg.png
email: araft50@yahoo.com
copyright_name: ARAF91
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ARAF91
learn_profile: ARAF91
email_username: araft50@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
